In [1]:
import pandas as pd
import numpy as np

In [2]:
news = pd.read_csv("dataF.csv",encoding='utf-8',index_col=0)

In [3]:
news = news.sample(frac=1)
print(news.head(10))
news.shape

                                                    data           flag
13645  বাংলা খেয়ালের প্রসার প্রচার লক্ষ্য রাতব্যাপী ...  entertainment
12217  সন্ত্রাস নাশকতা নৈরাজ্য প্রতিবাদ ডাকা সমাবেশ য...          crime
19392  পুঁজি অভাব নাটোরের লালপুর উপজেলা ধানাইদহপাড়া...      economics
30556  নোয়াখালীতে সার্কভুক্ত দেশ যুব প্রতিনিধি হয়েছ...    environment
21233  ঢাকা জুন ০৫ বিডিনিউজ টোয়েন্টিফোর ডটকম প্রয়াত র...    environment
24081  জাতীয় সংসদ সম্প্রতি পাস হওয়া সংবিধান ষোড়শ সংশ...        opinion
3232   আঙ্কারা নভেম্বও ৩০ বিডিনিউজ টুয়েন্টিফোর ডটকম/র...       accident
22820  ঢাকা নভেম্বর ১৩ বিডিনিউজ টোয়েন্টিফোর ডটকম বিডি...   science_tech
6774   মঙ্গলবার গাজীপুর মীরেরবাজারে ঘোড়াশাল টঙ্গী সড়ক...       accident
14442  ভারত মেঘালয় রাজ্য কয়লা উত্তোলন প্রক্রিয়া জটিল...      economics


(31912, 2)

In [4]:
labels = list(set(news.flag))

for label in labels:
    print( "{:20} --- {} samples".format( label, news[ news.flag == label ].shape[0]  ))

politics             --- 2660 samples
art                  --- 2659 samples
education            --- 2659 samples
opinion              --- 2660 samples
entertainment        --- 2659 samples
crime                --- 2659 samples
science_tech         --- 2660 samples
environment          --- 2659 samples
international        --- 2659 samples
sports               --- 2660 samples
accident             --- 2659 samples
economics            --- 2659 samples


In [5]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
ncategories = encoder.fit_transform(news['flag'])
news['label'] = np.array(ncategories)
news.head(10)

data           flag  label
13645  বাংলা খেয়ালের প্রসার প্রচার লক্ষ্য রাতব্যাপী ...  entertainment      5
12217  সন্ত্রাস নাশকতা নৈরাজ্য প্রতিবাদ ডাকা সমাবেশ য...          crime      2
19392  পুঁজি অভাব নাটোরের লালপুর উপজেলা ধানাইদহপাড়া...      economics      3
30556  নোয়াখালীতে সার্কভুক্ত দেশ যুব প্রতিনিধি হয়েছ...    environment      6
21233  ঢাকা জুন ০৫ বিডিনিউজ টোয়েন্টিফোর ডটকম প্রয়াত র...    environment      6
24081  জাতীয় সংসদ সম্প্রতি পাস হওয়া সংবিধান ষোড়শ সংশ...        opinion      8
3232   আঙ্কারা নভেম্বও ৩০ বিডিনিউজ টুয়েন্টিফোর ডটকম/র...       accident      0
22820  ঢাকা নভেম্বর ১৩ বিডিনিউজ টোয়েন্টিফোর ডটকম বিডি...   science_tech     10
6774   মঙ্গলবার গাজীপুর মীরেরবাজারে ঘোড়াশাল টঙ্গী সড়ক...       accident      0
14442  ভারত মেঘালয় রাজ্য কয়লা উত্তোলন প্রক্রিয়া জটিল...      economics      3

In [6]:
news.shape

(31912, 3)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(news["data"], news["flag"],test_size=0.2, random_state=42)

In [8]:
X_train.head(3)

27596    বিশিষ্ট নাগরিক উদ্যোগে জাতীয় সংলাপ উদ্যোগকে ...
30754    রংপুর বেগম রোকেয়া বিশ্ববিদ্যালয় সন্ত্রাসী হাম...
5129     বগুড়ার আমতলী উপজেলায় শুক্রবার রাত ট্রলি মোটর...
Name: data, dtype: object

# CountVectorizer

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
X_train_vectorized = vect.fit_transform(X_train.values.astype('unicode'))

# TF-IDF Vectorizer

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector = TfidfVectorizer()
X_train_vect = vector.fit_transform(X_train.values.astype('unicode'))


# CV-SVM

In [11]:
from sklearn.svm import SVC
svm = SVC(kernel='poly', gamma='auto')
svm.fit(X_train_vectorized, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_testCV = svm.predict(vect.transform(y_test.values.astype('unicode')))
y_predCV = svm.predict(vect.transform(X_test.values.astype('unicode')))

# TFIDF-SVM

In [124]:
svm.fit(X_train_vect, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [125]:
y_testTF = svm.predict(vector.transform(y_test.values.astype('unicode')))
y_predTF = svm.predict(vector.transform(X_test.values.astype('unicode')))

# Accuracy of CV-SVM

In [120]:
from sklearn.metrics import accuracy_score
accuracy_score(y_testCV, y_predCV)*100

99.51433495221681

In [121]:
from sklearn.metrics import precision_score
print(precision_score(y_testCV, y_predCV, average=None)*100)

[  0. 100.   0.]


In [122]:
from sklearn.metrics import classification_report
print(classification_report(y_testCV, y_predCV))

              precision    recall  f1-score   support

         art       0.00      0.00      0.00         0
   education       1.00      1.00      1.00      6383
     opinion       0.00      0.00      0.00         0

   micro avg       1.00      1.00      1.00      6383
   macro avg       0.33      0.33      0.33      6383
weighted avg       1.00      1.00      1.00      6383



In [123]:
from sklearn.metrics import f1_score
print(f1_score(y_testCV, y_predCV, average=None)*100)

[ 0.         99.75657636  0.        ]


# Accuracy of TFIDF-SVM

In [126]:

accuracy_score(y_testTF, y_predTF)*100

100.0

In [127]:

print(precision_score(y_testTF, y_predTF, average=None)*100)

[100.]


In [128]:

print(classification_report(y_testTF, y_predTF))

              precision    recall  f1-score   support

         art       1.00      1.00      1.00      6383

   micro avg       1.00      1.00      1.00      6383
   macro avg       1.00      1.00      1.00      6383
weighted avg       1.00      1.00      1.00      6383



In [129]:

print(f1_score(y_testTF, y_predTF, average=None)*100)

[100.]


# CV-DecisionTree

In [142]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 5,
 max_depth=2, min_samples_leaf=7)
clf_entropy.fit(X_train_vectorized, y_train)

##### Another model
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 5,
                               max_depth=2, min_samples_leaf=7)
clf_gini.fit(X_train_vectorized, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=7, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=5,
            splitter='best')

In [143]:
y_testDTE = clf_entropy.predict(vect.transform(y_test.values.astype('unicode')))
y_predDTE = clf_entropy.predict(vect.transform(X_test.values.astype('unicode')))

In [144]:
y_testDTG = clf_gini.predict(vect.transform(y_test.values.astype('unicode')))
y_predDTG = clf_gini.predict(vect.transform(X_test.values.astype('unicode')))

# TFIDF-DecisionTree

In [145]:
clf_entropy.fit(X_train_vect, y_train)

clf_gini.fit(X_train_vect, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=7, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=5,
            splitter='best')

In [146]:
y_testDTE_TF = clf_entropy.predict(vector.transform(y_test.values.astype('unicode')))
y_predDTE_TF = clf_entropy.predict(vector.transform(X_test.values.astype('unicode')))

In [147]:
y_testDTG_TF = clf_gini.predict(vector.transform(y_test.values.astype('unicode')))
y_predDTG_TF = clf_gini.predict(vector.transform(X_test.values.astype('unicode')))

# Accuracy of CV-DecisionTree

In [149]:

accuracy_score(y_testDTE, y_predDTE)*100

66.56744477518409

In [150]:

accuracy_score(y_testDTG, y_predDTG)*100

66.56744477518409

In [151]:

print(precision_score(y_testDTE, y_predDTE, average=None)*100)

[  0. 100.   0.]


In [152]:

print(precision_score(y_testDTG, y_predDTG, average=None)*100)

[  0. 100.   0.   0.]


In [172]:

print(classification_report(y_testDTE, y_predDTE))

              precision    recall  f1-score   support

    accident       0.00      0.00      0.00         0
   education       1.00      0.67      0.80      6383
    politics       0.00      0.00      0.00         0

   micro avg       0.67      0.67      0.67      6383
   macro avg       0.33      0.22      0.27      6383
weighted avg       1.00      0.67      0.80      6383



In [173]:

print(classification_report(y_testDTG, y_predDTG))

              precision    recall  f1-score   support

    accident       0.00      0.00      0.00         0
   education       1.00      0.67      0.80      6383
 environment       0.00      0.00      0.00         0
    politics       0.00      0.00      0.00         0

   micro avg       0.67      0.67      0.67      6383
   macro avg       0.25      0.17      0.20      6383
weighted avg       1.00      0.67      0.80      6383



In [175]:

print(f1_score(y_testDTE, y_predDTE, average=None)*100)

[ 0.         79.92851768  0.        ]


In [176]:

print(f1_score(y_testDTG, y_predDTG, average=None)*100)

[ 0.         79.92851768  0.          0.        ]


# Accuracy of TFIDF-DecisionTree

In [177]:

accuracy_score(y_testDTE_TF, y_predDTE_TF)*100

72.55209149302836

In [178]:

accuracy_score(y_testDTG_TF, y_predDTG_TF)*100

74.88641704527652

In [179]:

print(precision_score(y_testDTE_TF, y_predDTE_TF, average=None)*100)

[  0. 100.   0.]


In [180]:

print(precision_score(y_testDTG_TF, y_predDTG_TF, average=None)*100)

[  0.   0. 100.   0.]


In [161]:
from sklearn.metrics import classification_report
print(classification_report(y_testDTE_TF, y_predDTE_TF))

              precision    recall  f1-score   support

    accident       0.00      0.00      0.00         0
   education       1.00      0.73      0.84      6383
    politics       0.00      0.00      0.00         0

   micro avg       0.73      0.73      0.73      6383
   macro avg       0.33      0.24      0.28      6383
weighted avg       1.00      0.73      0.84      6383



In [162]:
from sklearn.metrics import classification_report
print(classification_report(y_testDTG_TF, y_predDTG_TF))

              precision    recall  f1-score   support

    accident       0.00      0.00      0.00         0
       crime       0.00      0.00      0.00         0
   education       1.00      0.75      0.86      6383
    politics       0.00      0.00      0.00         0

   micro avg       0.75      0.75      0.75      6383
   macro avg       0.25      0.19      0.21      6383
weighted avg       1.00      0.75      0.86      6383



In [163]:
from sklearn.metrics import f1_score
print(f1_score(y_testDTE_TF, y_predDTE_TF, average=None)*100)

[ 0.         84.09297258  0.        ]


In [164]:
from sklearn.metrics import f1_score
print(f1_score(y_testDTG_TF, y_predDTG_TF, average=None)*100)

[ 0.          0.         85.64006092  0.        ]
